spring:
  data:
    redis:
      host: api-quote-calculator-redis-test.redis.cache.windows.net
      port: 6380
      username: 13feedc4-37e7-453e-902b-4309b3718a7f
      ssl:
        enabled: true
      azure:
        passwordless-enabled: true