spring:
  data:
    redis:
      host: api-quote-calculator-redis-test.redis.cache.windows.net
      port: 6380
      username: c2e0ee3b-fc80-4e0f-ae10-770a0858e7dd
      ssl:
        enabled: true
      azure:
        passwordless-enabled: true
